export enum NotificationType {
    APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
    APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
    APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
    USER_REGISTERED = 'USER_REGISTERED',
}